import commonjs from "@rollup/plugin-commonjs";
import resolve from "@rollup/plugin-node-resolve";
import typescript from "@rollup/plugin-typescript";
import builtins from "rollup-plugin-node-builtins";
import globals from "rollup-plugin-node-globals";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository (https://github.com/leonhma/obsidian-functionplot)
*/
`;

export default {
    input: "main.ts",
    output: {
        format: "iife",
        file: "main.js",
        sourcemap: "inline",
        exports: "default",
        banner
    },
    external: ["obsidian"],
    plugins: [
        typescript(),
        commonjs(),
        resolve({
            browser: true,
        }),
        builtins(),
        globals()
    ],
};
